/* Joystick module driver
 * PC1  → ADC2 Channel 11 (X-axis)
 * PC2  → ADC2 Channel 12 (Y-axis)
 * PE10 → GPIO Input Pull-Up (button, active LOW)
 *
 * ADC2 is used in software-triggered single-conversion mode.
 * hadc2 handle is defined/initialised by CubeMX-generated code.
 * This module only adds the polling task on top.
 */

#include "joystick.h"

/* ── Thresholds ─────────────────────────────────────────────────────────── */
#define JOY_CENTRE     2048u
#define JOY_DEADZONE    750u   /* wide zone — avoids false triggers and accidental switches */
#define JOY_HIGH_THR   (JOY_CENTRE + JOY_DEADZONE)   /* 2448 */
#define JOY_LOW_THR    (JOY_CENTRE - JOY_DEADZONE)   /* 1648 */

#define JOY_BTN_PIN    GPIO_PIN_10
#define JOY_BTN_PORT   GPIOE

/* Minimum ms between two joystick events (auto-repeat rate) */
#define JOY_REPEAT_MS  350u

/* ── External ADC handle (generated by CubeMX in adc.c / main.c) ────────── */
extern ADC_HandleTypeDef hadc2;

/* ── State ──────────────────────────────────────────────────────────────── */
static uint16_t   s_x = 2048, s_y = 2048;
static uint8_t    s_btn_prev    = 0;
static JoyEvent_t s_pending     = JOY_NONE;
static uint32_t   s_last_event_tick = 0;
static uint8_t    s_axis_locked = 0u; /* 1 = axis fired; wait for return to centre */

/* ── Internal: single ADC2 conversion on given channel ──────────────────── */
static uint16_t adc2_read(uint32_t channel)
{
    ADC_ChannelConfTypeDef cfg = {0};
    cfg.Channel      = channel;
    cfg.Rank         = 1;
    cfg.SamplingTime = ADC_SAMPLETIME_56CYCLES;
    HAL_ADC_ConfigChannel(&hadc2, &cfg);

    HAL_ADC_Start(&hadc2);
    if (HAL_ADC_PollForConversion(&hadc2, 5) == HAL_OK)
        return (uint16_t)HAL_ADC_GetValue(&hadc2);
    return JOY_CENTRE;
}

/* ── Public API ─────────────────────────────────────────────────────────── */

void Joystick_Init(void)
{
    /* GPIO PE10 already configured by CubeMX as Input Pull-Up */

    /* Warm-up: flush ADC settling transients (capacitor charge-up takes ~5 ms).
     * Without this the first reading often falls outside the deadzone and
     * generates spurious JOY_RIGHT events that cycle through all modes. */
    for (int i = 0; i < 10; i++)
    {
        adc2_read(ADC_CHANNEL_11);
        adc2_read(ADC_CHANNEL_12);
        HAL_Delay(10);          /* 10 × 10 ms = 100 ms total */
    }

    s_x = adc2_read(ADC_CHANNEL_11);
    s_y = adc2_read(ADC_CHANNEL_12);

    s_btn_prev    = 0;
    s_pending     = JOY_NONE;
    s_axis_locked = 0u;

    /* Suppress any events for the first REPEAT interval after init */
    s_last_event_tick = HAL_GetTick();
}

void Joystick_Update(void)
{
    uint32_t now = HAL_GetTick();

    /* Only generate a new event after repeat delay */
    if ((now - s_last_event_tick) < JOY_REPEAT_MS) return;

    /* Read both axes */
    s_x = adc2_read(ADC_CHANNEL_11);   /* PC1 */
    s_y = adc2_read(ADC_CHANNEL_12);   /* PC2 */

    /* Read button (active LOW) */
    uint8_t btn_now = (HAL_GPIO_ReadPin(JOY_BTN_PORT, JOY_BTN_PIN) == GPIO_PIN_RESET) ? 1u : 0u;

    /* Unlock axis when joystick returns to centre deadzone */
    if (s_x >= JOY_LOW_THR && s_x <= JOY_HIGH_THR &&
        s_y >= JOY_LOW_THR && s_y <= JOY_HIGH_THR)
    {
        s_axis_locked = 0u;
    }

    JoyEvent_t ev = JOY_NONE;

    /* Button: detect press edge */
    if (btn_now && !s_btn_prev)
        ev = JOY_PRESS;

    /* Axis events — only when not locked (requires return-to-centre between events) */
    if (ev == JOY_NONE && !s_axis_locked)
    {
        if      (s_y < JOY_LOW_THR)  { ev = JOY_UP;    s_axis_locked = 1u; }
        else if (s_y > JOY_HIGH_THR) { ev = JOY_DOWN;  s_axis_locked = 1u; }
        else if (s_x < JOY_LOW_THR)  { ev = JOY_LEFT;  s_axis_locked = 1u; }
        else if (s_x > JOY_HIGH_THR) { ev = JOY_RIGHT; s_axis_locked = 1u; }
    }

    s_btn_prev = btn_now;

    if (ev != JOY_NONE)
    {
        s_pending = ev;
        s_last_event_tick = now;
    }
}

JoyEvent_t Joystick_GetEvent(void)
{
    JoyEvent_t ev = s_pending;
    s_pending = JOY_NONE;
    return ev;
}

uint8_t Joystick_IsPressed(void)
{
    return (HAL_GPIO_ReadPin(JOY_BTN_PORT, JOY_BTN_PIN) == GPIO_PIN_RESET) ? 1u : 0u;
}

uint16_t Joystick_GetX(void) { return s_x; }
uint16_t Joystick_GetY(void) { return s_y; }
