/* microphone.c — MAX9814 analog microphone capture and pitch detection
 *
 * Hardware:
 *   PC3  = ADC1_IN13 ← MAX9814 OUT
 *   TIM3 triggers ADC1 at MIC_FS_HZ (configured in CubeMX)
 *   DMA2 Stream0 — circular, transfers 16-bit ADC values to dma_buf[]
 *
 * Adjust MIC_FS_HZ to match your CubeMX TIM3 settings:
 *   f = TIM_CLK_MHz × 1e6 / ((Prescaler+1) × (Period+1))
 *   TIM_CLK = APB1 × 2 = 24 MHz × 2 = 48 MHz  (at SYSCLK=96 MHz, APB1 pre=4)
 *   Example: 48 MHz / (84 × 63) ≈ 9 070 Hz   → set MIC_FS_HZ 9070
 *   Example: 48 MHz / (3 × 1000) = 16 000 Hz  (faster, but SD writes too slow)
 *   Current config: 48 MHz / (84 × 63) ≈ 9 070 Hz  (Prescaler=83, Period=62).
 *
 * Pitch detection: normalized autocorrelation + parabolic interpolation
 * (same algorithm as the original PDM version, unchanged).
 */

#include "microphone.h"
#include "main.h"
#include "recorder.h"
#include "chord.h"
#include <math.h>
#include <string.h>

/* -----------------------------------------------------------------------
 * Configuration
 * --------------------------------------------------------------------- */
#define MIC_FS_HZ        9070.0f    /* effective sample rate — 48 MHz / 84 / 63 ≈ 9070 Hz */

#define DMA_HALF         1024u      /* half-buffer size — 1024/9070 ≈ 113 ms between DMA callbacks */
#define DMA_BUF_SIZE     (DMA_HALF * 2u)

#define PCM_WIN_SIZE     1024u      /* autocorrelation window (~64 ms @ 16 kHz) */
#define LAG_MIN          14         /* 16000 / ~1143 Hz */
#define LAG_MAX          300        /* 16000 / ~53 Hz   */

#define SILENCE_E0       8000000LL

/* IIR LPF coefficients (fc ≈ 400 Hz @ 16 kHz, suppresses upper harmonics) */
#define LPF_ALPHA        0.9172f
#define LPF_BETA         0.0828f

/* Transient suppression */
#define TRANSIENT_RATIO      3.5f
#define TRANSIENT_HOLD_WIN   2u
#define ENERGY_EMA_ALPHA     0.85f

/* Dynamic confidence thresholds */
#define CONFIDENCE_THR_BASE  0.38f
#define CONFIDENCE_THR_DELTA 0.15f

/* ADC mid-scale (12-bit → 2048 = 0V, MAX9814 biased at VCC/2) */
#define ADC_MIDSCALE     2048

/* -----------------------------------------------------------------------
 * Buffers and state
 * --------------------------------------------------------------------- */
static uint16_t  dma_buf[DMA_BUF_SIZE];   /* raw ADC values from DMA     */
static int16_t   pcm_win[PCM_WIN_SIZE];   /* signed PCM accumulation      */
static uint32_t  pcm_idx      = 0;
static volatile
       uint8_t   pitch_ready  = 0;

/* Last filled half-buffer (for sampler recording) */
static int16_t   rec_half[DMA_HALF];
static volatile
       uint16_t  rec_avail    = 0;

/* Half-buffer ready flags: the DMA ISR only records WHICH half completed;
 * the heavy filtering/copy work runs later in MIC_Service() from the main
 * loop, OUT of interrupt context.  This keeps the bit-banged TTP229 keypad
 * read from being stalled mid-word by a long mic interrupt. */
static volatile
       uint8_t   s_half_pending = 0u;     /* bit0 = first half, bit1 = second */

/* On/off guard so MIC_Start()/MIC_Stop() are idempotent.  The main loop
 * drives the mic on-demand (only Tuner / Chord / an active recording need
 * it); keeping the ADC idle the rest of the time stops its ~9 kHz sampling
 * from coupling noise into the bit-banged TTP229 keypad. */
static volatile
       uint8_t   mic_running    = 0u;

/* -----------------------------------------------------------------------
 * Results
 * --------------------------------------------------------------------- */
static float  detected_freq = 0.0f;
static uint8_t signal_valid = 0;

/* Transient / energy state */
static float   energy_avg     = 0.0f;
static uint8_t transient_hold = 0;

/* -----------------------------------------------------------------------
 * External ADC handle (generated by CubeMX)
 * --------------------------------------------------------------------- */
extern ADC_HandleTypeDef hadc1;
DMA_HandleTypeDef hdma_adc1;   /* extern in microphone.h */

/* -----------------------------------------------------------------------
 * Public API
 * --------------------------------------------------------------------- */

void MIC_Init(void)
{
    /* ADC1, TIM3, DMA2 Stream0 are fully initialised by CubeMX-generated
     * MX_ADC1_Init(), MX_TIM3_Init(), MX_DMA_Init() in main.c.
     * Nothing extra to do here unless you want runtime reconfiguration.   */
}

void MIC_Start(void)
{
    if (mic_running) return;            /* idempotent — already capturing */

    pcm_idx        = 0;
    pitch_ready    = 0;
    detected_freq  = 0.0f;
    signal_valid   = 0;
    rec_avail      = 0;
    s_half_pending = 0u;               /* drop any stale half flags */

    /* Start ADC in DMA circular mode — TIM3 TRGO triggers each conversion */
    HAL_ADC_Start_DMA(&hadc1, (uint32_t*)dma_buf, DMA_BUF_SIZE);

    /* Start TIM3 so it generates TRGO pulses */
    HAL_TIM_Base_Start(&htim3);

    mic_running = 1u;
}

void MIC_Stop(void)
{
    if (!mic_running) return;           /* idempotent — already idle */

    HAL_TIM_Base_Stop(&htim3);
    HAL_ADC_Stop_DMA(&hadc1);
    s_half_pending = 0u;               /* drop any pending halves */

    mic_running = 0u;
}

float  MIC_GetFrequency(void)  { return detected_freq; }
uint8_t MIC_IsSignalValid(void) { return signal_valid;  }  /* returns uint8_t as per header */

const int16_t* MIC_GetBuffer(uint16_t *out_samples)
{
    if (rec_avail == 0) { *out_samples = 0; return NULL; }
    *out_samples = rec_avail;
    rec_avail    = 0;
    return rec_half;
}

/* -----------------------------------------------------------------------
 * Internal: process one half-buffer of raw ADC samples
 * --------------------------------------------------------------------- */
static void Process_Half(const uint16_t *adc_half, uint16_t len)
{
    static float lpf_y = 0.0f;

    for (uint16_t i = 0; i < len; i++)
    {
        /* Convert unsigned 12-bit ADC to signed int16 */
        int16_t s = (int16_t)((int32_t)adc_half[i] - ADC_MIDSCALE) << 3; /* ×8 for gain */

        /* 1st-order IIR LPF — remove inharmonic overtones for pitch detect */
        lpf_y = LPF_ALPHA * lpf_y + LPF_BETA * (float)s;
        pcm_win[pcm_idx++] = (int16_t)lpf_y;
        if (pcm_idx >= PCM_WIN_SIZE) {
            pcm_idx    = 0;
            pitch_ready = 1;
        }

        /* Store unfiltered for recorder/sampler (overtones needed there) */
        rec_half[i] = s;
    }
    rec_avail = len;

    /* Feed chord detector and WAV recorder with raw PCM */
    REC_FeedSamples(rec_half, len);
    CHORD_FeedSamples(rec_half, len);
}

/* -----------------------------------------------------------------------
 * MIC_Service — run the deferred half-buffer processing from the main loop.
 * The DMA ISR only flags which half is ready (s_half_pending); the heavy
 * filtering/copy work happens HERE, out of interrupt context, so it can
 * never stall the bit-banged TTP229 keypad read.  Safe because each half
 * spans ~113 ms (1024 samples @ 9070 Hz) and the main loop runs far faster.
 * Call once per main-loop iteration, BEFORE MIC_Process()/Task_Recorder().
 * --------------------------------------------------------------------- */
void MIC_Service(void)
{
    uint8_t pending;

    /* Atomically read and clear the pending flags */
    uint32_t primask = __get_PRIMASK();
    __disable_irq();
    pending        = s_half_pending;
    s_half_pending = 0u;
    __set_PRIMASK(primask);

    /* Halves fill in order, so if both are pending process first then second */
    if (pending & 0x01u) Process_Half(dma_buf,            DMA_HALF);
    if (pending & 0x02u) Process_Half(dma_buf + DMA_HALF, DMA_HALF);
}

/* -----------------------------------------------------------------------
 * Pitch detection — normalized autocorrelation + parabolic interpolation
 * (algorithm unchanged from PDM version)
 * --------------------------------------------------------------------- */
void MIC_Process(void)
{
    if (!pitch_ready) return;
    pitch_ready = 0;

    /* DC removal and total energy */
    int64_t dc_sum = 0;
    for (int i = 0; i < (int)PCM_WIN_SIZE; i++) dc_sum += pcm_win[i];
    int16_t dc = (int16_t)(dc_sum / (int64_t)PCM_WIN_SIZE);

    int64_t e0 = 0;
    for (int i = 0; i < (int)PCM_WIN_SIZE; i++) {
        int32_t s = (int32_t)pcm_win[i] - dc;
        e0 += s * s;
    }

    if (e0 < SILENCE_E0) {
        signal_valid  = 0;
        detected_freq = 0.0f;
        transient_hold = 0;
        energy_avg   *= 0.9f;
        return;
    }

    float energy_norm = (float)e0 / (float)PCM_WIN_SIZE;

    if (energy_avg > 1e5f && energy_norm > energy_avg * TRANSIENT_RATIO)
        transient_hold = TRANSIENT_HOLD_WIN;

    energy_avg = ENERGY_EMA_ALPHA * energy_avg
               + (1.0f - ENERGY_EMA_ALPHA) * energy_norm;

    if (transient_hold > 0) {
        transient_hold--;
        signal_valid  = 0;
        detected_freq = 0.0f;
        return;
    }

    float conf_thr = CONFIDENCE_THR_BASE;
    if (energy_avg > 1.0f) {
        float ratio = energy_norm / energy_avg;
        if (ratio < 0.5f)
            conf_thr += CONFIDENCE_THR_DELTA * (1.0f - ratio * 2.0f);
    }

    int   best_lag  = 0;
    float best_corr = -2.0f;

    for (int lag = LAG_MIN; lag <= LAG_MAX; lag++) {
        int64_t r = 0, e = 0;
        int N = (int)PCM_WIN_SIZE - lag;
        for (int i = 0; i < N; i++) {
            int32_t xi  = (int32_t)pcm_win[i]       - dc;
            int32_t xil = (int32_t)pcm_win[i + lag] - dc;
            r += xi * xil;
            e += xil * xil;
        }
        if (e == 0) continue;
        float corr = (float)r / sqrtf((float)e0 * (float)e / (float)N);
        if (corr > best_corr) { best_corr = corr; best_lag = lag; }
    }

    if (best_corr < conf_thr || best_lag == 0) {
        signal_valid  = 0;
        detected_freq = 0.0f;
        return;
    }

    float precise_lag = (float)best_lag;
    if (best_lag > LAG_MIN && best_lag < LAG_MAX) {
        float r_adj[2];
        for (int k = 0; k < 2; k++) {
            int lag = best_lag - 1 + k * 2;
            int64_t r = 0, e = 0;
            int N = (int)PCM_WIN_SIZE - lag;
            for (int i = 0; i < N; i++) {
                int32_t xi  = (int32_t)pcm_win[i]       - dc;
                int32_t xil = (int32_t)pcm_win[i + lag] - dc;
                r += xi * xil;
                e += xil * xil;
            }
            r_adj[k] = (e > 0) ? (float)r / sqrtf((float)e0 * (float)e / (float)N)
                                : best_corr;
        }
        float denom = r_adj[0] - 2.0f * best_corr + r_adj[1];
        if (fabsf(denom) > 1e-6f)
            precise_lag += 0.5f * (r_adj[0] - r_adj[1]) / denom;
    }

    detected_freq = MIC_FS_HZ / precise_lag;
    signal_valid  = 1;
}

/* -----------------------------------------------------------------------
 * HAL ADC DMA callbacks (override weak symbols)
 * --------------------------------------------------------------------- */
void HAL_ADC_ConvHalfCpltCallback(ADC_HandleTypeDef *hadc)
{
    if (hadc->Instance == ADC1)
        s_half_pending |= 0x01u;   /* first half ready — processed in MIC_Service() */
}

void HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef *hadc)
{
    if (hadc->Instance == ADC1)
        s_half_pending |= 0x02u;   /* second half ready — processed in MIC_Service() */
}
